version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: typegraphql-example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      # - "5432:5432"
      - "4420:5432"
  web:
    image: type-graphql-01
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6378:6379' 
      # - '6379:6379'